<a href="https://colab.research.google.com/github/Eunwoo-1213/BIGDATA_ANALYZE/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.power(np.arange(10), 2) # power는 제곱
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [3]:
print(a[3])
print(a[-2])

9
64


In [4]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [5]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [6]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [12]:
a[:, 1, 1]

array([ 5, 17])

In [13]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [14]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.transpose(a) # a.transpose(), a.T 도 가능

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x[1]

np.int64(1)

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
x[ [1] ]

array([1])

In [21]:
x[ [1, 1, 2, 5]]

array([1, 1, 2, 5])

In [23]:
x[[ 1, 1, 2, 5, -1 ,-2 , -5]]

array([1, 1, 2, 5, 9, 8, 5])

In [26]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [27]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
x[ [6, 5]]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [29]:
x[0, 1]

np.int64(1)

In [30]:
x[[0 , 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [31]:
x[: , 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [34]:
x[[0] , [1]]

array([1])

In [35]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [36]:
x[:, [1, 2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [37]:
x[:, [2, 1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [38]:
x[[ 1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [40]:
x[ [1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [41]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [42]:
x[[1, 3] , [2, 2]]

array([10, 26])

In [52]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [53]:
x[ [0, 2, 4], 1] # 0행 2행 4행의 1열

array([ 1, 17, 33])

In [56]:
x[ [0, 2, 4], :2] # 0행 2행 4행의 0, 1 열

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [58]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [59]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [60]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [61]:
a[ [2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [64]:
# a[ [2, 3]]이랑 똑같음
a[ np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [67]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [68]:
a[np.arange(2,4)] [:, [1,0]] # 2, 3행의 1, 0열

array([[17, 16],
       [25, 24]])

In [69]:
a[np.arange(2, 4)] [:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [72]:
np.arange(-1, -8 ,-1)

array([-1, -2, -3, -4, -5, -6, -7])

In [74]:
a[np.arange(2, 5)] [:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 챕터 3 과제