<a href="https://colab.research.google.com/github/Eunwoo-1213/BIGDATA_ANALYZE/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.power(np.arange(10), 2) # power는 제곱
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [ ]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[:, 1, 1]

array([ 5, 17])

In [ ]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a) # a.transpose(), a.T 도 가능

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[ [1] ]

array([1])

In [ ]:
x[ [1, 1, 2, 5]]

array([1, 1, 2, 5])

In [ ]:
x[[ 1, 1, 2, 5, -1 ,-2 , -5]]

array([1, 1, 2, 5, 9, 8, 5])

In [ ]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [36]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[ [6, 5]]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[[0 , 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[: , 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[[0] , [1]]

array([1])

In [ ]:
x[:, [1]]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[:, [1, 2]]

array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [ ]:
x[:, [2, 1]]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[[ 1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[ [1,3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[[1, 3] , [2, 2]]

array([10, 26])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 2, 4], 1] # 0행 2행 4행의 1열

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], :2] # 0행 2행 4행의 0, 1 열

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ [2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
# a[ [2, 3]]이랑 똑같음
a[ np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,4)] [:, [1,0]] # 2, 3행의 1, 0열

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2, 4)] [:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
np.arange(-1, -8 ,-1)

array([-1, -2, -3, -4, -5, -6, -7])

In [ ]:
a[np.arange(2, 5)] [:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 챕터 3 과제

##다차원 배열 ndarray

In [12]:
import numpy as np

a = np.ndarray((1, 2, 3))
a

array([[[2.99937372e-319, 0.00000000e+000, 2.14321575e-312],
        [2.22809558e-312, 2.46151512e-312, 5.68175493e-322]]])

In [13]:
import numpy as np

a = np.ndarray((1, 2, 3), dtype=int)
a

array([[[       60708,            0, 433791696928],
        [450971566200, 498216206451,          115]]])

In [14]:
a = np.ndarray((1, 2, 3), int)
a

array([[[      253673084,               0, 132329219411888],
        [       10847616,        10860928, 132329220139056]]])

### 내장함수 array

In [15]:
import numpy as np
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [16]:
type(a)

numpy.ndarray

In [17]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [18]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


### numpy.arrange()

In [19]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [20]:
import numpy as np

print(np.arange(2, 0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


### reshape()



In [21]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.reshape(a, (2, 6 ))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### linespace()

In [23]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [24]:
(3-1)/(50-1)

0.04081632653061224

In [25]:
np.linspace(2.0, 3.0, retstep = True, endpoint=False)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

### numpyfull()

In [26]:
np.full([2, 3], 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [27]:
np.full([2, 3], (7, 7, 7))

array([[7, 7, 7],
       [7, 7, 7]])

In [28]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

### 배열과 스칼라의 연산

In [29]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [30]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


### 배열함수

In [31]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [32]:
a.sum()

np.int64(46)

In [33]:
a.sum(axis = 0) # 열의 합

array([16, 30])

In [35]:
a.sum(axis = 1) # 행의 합

array([30, 13,  3])

In [42]:
a[:, ] # a[:, :]와 같

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
# 역순 배열
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [44]:
# 마지막 행과 열을 제외
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

### 3차원 배열

In [45]:
a = np.arange(24).reshape(2,3,4)

In [46]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [52]:
a[:,1,1]

array([ 5, 17])

In [49]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

### 3차원 배열에서 1차원 배열로 만드는 ndarray.ravel()

In [53]:
a = np.arange(12).reshape(2, 3, 2)
a
# 3행 2열인 2차원 배열 2개

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [54]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 행과 열을 바꾸는 transpose()

In [55]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

###swapaxes

In [60]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [62]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

### view



In [63]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [64]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [65]:
v[2] = 200
v


array([  0,   1, 200,   3,   4])

In [66]:
org

array([  0,   1, 200,   3,   4])

copy

In [67]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [68]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [69]:
c[2] = 200
c


array([  0,   1, 200,   3,   4])

In [70]:
org


array([0, 1, 2, 3, 4])