<a href="https://colab.research.google.com/github/Eunwoo-1213/BIGDATA_ANALYZE/blob/main/04w_array_stack_split_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(1, 13).reshape(3,4)
c = np.arange(1, 6, 2)
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

### hstack(), column stack()

In [ ]:
c[:, None]

array([[1],
       [3],
       [5]])

In [ ]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [ ]:
cc = np.expand_dims(c, axis = 1)
cc

array([[1],
       [3],
       [5]])

In [ ]:
np.hstack((a,cc)) # = column_stack()

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### vstack(), row stack() 기능 같음

### np.c_[] 1행 2차원배열

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.c_[a, b], np.column_stack((a,b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

### np.r_[]

### 난수 기초와 생성

In [21]:
import numpy as np

rg = np.random.default_rng(12)
rg.random() # (0, 1) 실수 난수

0.5118216247002567

In [26]:
rg.random()

0.42332644897257565

In [45]:
rg.random((3, 4))

array([[0.07521111, 0.96286458, 0.54001121, 0.7738943 ],
       [0.52922281, 0.61157973, 0.03389225, 0.18679368],
       [0.6746894 , 0.5705646 , 0.15855503, 0.95202927]])

In [51]:
import numpy as np

rg = np.random.default_rng(12)
rg.integers(1,7,(3,4)) # 1 ~ 6 사이에 정수 난수

array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [53]:
import numpy as np

rg = np.random.default_rng(12)
rg.integers(low = 1, high = 10,size =(2,8)) # 1 ~ 9 사이에 정수 난수

array([[6, 3, 9, 9, 1, 2, 2, 2],
       [6, 4, 5, 3, 9, 7, 6, 2]])

In [57]:
import numpy as np

rg = np.random.default_rng(12)
rg.standard_normal(10) # 표준 정규 분포 실수 난수

array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [59]:
rg.standard_normal((3,4))

array([[-0.49737204, -0.11477278, -0.60545201, -0.59433942],
       [-0.28337538, -0.72841773,  0.76632779, -1.59608633],
       [ 0.82356213, -0.62556647, -0.54593996, -1.35084714]])

In [ ]:
import numpy as np
np.random.randing(1,10,5)

In [60]:
import numpy as np
np.random.randint(1,10,5)

array([8, 3, 5, 3, 5])

### 연습코딩

In [64]:
x = np.arange(1,7).reshape(2,3)
y = np.arange(7,13).reshape(2,3)
x , y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [65]:
np.vstack((a,b)) # 1D --> 2D a = [1, 2, 3] b = [4, 5, 6]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack((a,b)) # 1D 유지

array([1, 2, 3, 4, 5, 6])

In [70]:
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [67]:
np.vstack((x,y)) # 2D --> 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [73]:
np.column_stack((a,b)) # 1D --> 2D  (1차원 배열을 열로 나열함)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
np.column_stack((a,b)), np.c_[a, b] # 1D --> 2D

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [75]:
np.column_stack((x,y)), np.c_[x, y] # 2D --> 2D

(array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [78]:
m = np.arange(24).reshape(2,3,4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
n = np.arange(96).reshape(4,4,6) # 3차원 배열
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [80]:
np.split(n, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]]),
 array([[[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83],
         [84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]